const fs = require('fs');

const dictContent = fs.readFileSync('extracted_dict.json', 'utf8');
const jsCode = `// Autogenerated Bonekaku ID/EN dictionary
export const DICT = ${dictContent};
`;

fs.writeFileSync('frontend/src/context/i18nDict.js', jsCode, 'utf8');
console.log('Wrote frontend/src/context/i18nDict.js successfully!');
